
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mang Arblu
 */
public class layout extends javax.swing.JFrame {

    String temp = "";
    Double bt, hl, ti;
    
    public layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonHitung = new javax.swing.JButton();
        ButtonCobaLagi = new javax.swing.JButton();
        ButtonKeluar = new javax.swing.JButton();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldTinggi = new javax.swing.JTextField();
        TextFieldBeratBadan = new javax.swing.JTextField();
        RadioButtonPerempuan = new javax.swing.JRadioButton();
        RadioButtonLaki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextFieldIdeal = new javax.swing.JTextField();
        TextFieldDiagnosa2 = new javax.swing.JTextField();
        TextFieldDiagnosa1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("The Bold Font", 1, 24)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 240, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel2.setText("cm");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 110, 27, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 190, 80, 20);

        ButtonHitung.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        ButtonHitung.setText("Hitung");
        ButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitungActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonHitung);
        ButtonHitung.setBounds(30, 230, 90, 20);

        ButtonCobaLagi.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        ButtonCobaLagi.setText("Coba Lagi");
        ButtonCobaLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCobaLagiActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCobaLagi);
        ButtonCobaLagi.setBounds(120, 230, 110, 20);

        ButtonKeluar.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        ButtonKeluar.setText("Keluar");
        ButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKeluar);
        ButtonKeluar.setBounds(230, 230, 100, 20);

        TextFieldNama.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        TextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldNama);
        TextFieldNama.setBounds(140, 70, 150, 30);

        TextFieldTinggi.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        TextFieldTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTinggiActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldTinggi);
        TextFieldTinggi.setBounds(140, 110, 50, 30);

        TextFieldBeratBadan.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        getContentPane().add(TextFieldBeratBadan);
        TextFieldBeratBadan.setBounds(140, 150, 50, 30);

        buttonGroup1.add(RadioButtonPerempuan);
        RadioButtonPerempuan.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        RadioButtonPerempuan.setText("Perempuan");
        RadioButtonPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonPerempuan);
        RadioButtonPerempuan.setBounds(140, 190, 100, 20);

        buttonGroup1.add(RadioButtonLaki);
        RadioButtonLaki.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        RadioButtonLaki.setText("Laki-Laki");
        getContentPane().add(RadioButtonLaki);
        RadioButtonLaki.setBounds(240, 190, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel6.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 260, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 310, 200, 30);

        TextFieldIdeal.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        TextFieldIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdealActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldIdeal);
        TextFieldIdeal.setBounds(210, 260, 50, 30);

        TextFieldDiagnosa2.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        getContentPane().add(TextFieldDiagnosa2);
        TextFieldDiagnosa2.setBounds(50, 380, 270, 30);

        TextFieldDiagnosa1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        getContentPane().add(TextFieldDiagnosa1);
        TextFieldDiagnosa1.setBounds(50, 340, 270, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel8.setText("Nama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 70, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 260, 27, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 150, 27, 30);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 440);

        setBounds(0, 0, 388, 478);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaActionPerformed

    private void RadioButtonPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonPerempuanActionPerformed

    private void ButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitungActionPerformed
        if(TextFieldBeratBadan.getText().equals("")||TextFieldTinggi.getText().equals("")||TextFieldNama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak Isian belum diisi");
        }
        else if(RadioButtonLaki.isSelected()||RadioButtonPerempuan.isSelected()){
            try{
                Proses();
            }
            
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
            }
         
        }
        else{
            //JOptionPane.showMessageDialog(null, "Isikan Jenis Kelamin Anda");
            Object[] options = { "Pesan", "Batal", "Keluar" };
            int optionss = JOptionPane.showOptionDialog(null, "Total biaya keseluruhan adalah : Apakah anda yakin ingin memesan ini?", "Konfirmasi",
            JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, options, options[0]);
            
            if (optionss == 0){
                JOptionPane.showMessageDialog(null, "Terimakasih, Pesanan anda akan segera dikirim", "Terimakasih", JOptionPane.INFORMATION_MESSAGE);
            }
            
            else if( optionss == 1)
            {
            
            }
            
            else{
                dispose();
            }
           
        }
    }//GEN-LAST:event_ButtonHitungActionPerformed

    private void TextFieldTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTinggiActionPerformed

    private void ButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonKeluarActionPerformed

    private void ButtonCobaLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCobaLagiActionPerformed
        buttonGroup1.clearSelection();
        TextFieldNama.setText("");
        TextFieldTinggi.setText("");
        TextFieldBeratBadan.setText("");
        TextFieldIdeal.setText("");
        TextFieldDiagnosa1.setText("");
        TextFieldDiagnosa2.setText("");
    }//GEN-LAST:event_ButtonCobaLagiActionPerformed

    private void TextFieldIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCobaLagi;
    private javax.swing.JButton ButtonHitung;
    private javax.swing.JButton ButtonKeluar;
    private javax.swing.JRadioButton RadioButtonLaki;
    private javax.swing.JRadioButton RadioButtonPerempuan;
    private javax.swing.JTextField TextFieldBeratBadan;
    private javax.swing.JTextField TextFieldDiagnosa1;
    private javax.swing.JTextField TextFieldDiagnosa2;
    private javax.swing.JTextField TextFieldIdeal;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldTinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(TextFieldTinggi.getText());
        bt = Double.valueOf(TextFieldBeratBadan.getText());
        
        if(RadioButtonPerempuan.isSelected()){
        hl = (ti - 100) * 1;
        }
        else if(RadioButtonLaki.isSelected()){
            hl = (ti - 104) * 1;
        }
        temp = Double.toString(hl.intValue());
        
        if(hl < bt){
            TextFieldIdeal.setText(temp);
            TextFieldDiagnosa1.setText("Maaf "+ TextFieldNama.getText() + ", Sepertinya anda Overweight :(");
            TextFieldDiagnosa2.setText("Bayaklah berolahraga dan hindari makanan berkolestrol");
        }
        else if(hl> bt){
            TextFieldIdeal.setText(temp);
            TextFieldDiagnosa1.setText("Maaf "+ TextFieldNama.getText() + ", Sepertinya anda Underweight :(");
            TextFieldDiagnosa2.setText("Bayaklah mengkonsumsi makanan yang berkarbohidrat");
        }
        else{
            TextFieldIdeal.setText(temp);
            TextFieldDiagnosa1.setText("Hallo "+ TextFieldNama.getText() + ", Berat badan anda sudah ideal :)");
            TextFieldDiagnosa2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
        }
    }
}
